require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_mode:
  merge:
    - Include

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  Include:
    - .tomo/**/*.rb
    - /**/*.prawn
  Exclude:
    # ignore bin/* except for bin/setup
    - !ruby/regexp /<%= Regexp.quote(File.expand_path("bin", __dir__)) %>\/(?!setup).*/
    - .git/**/*
    - db/*schema.rb
    - lib/generators/**/*
    - lib/templates/**/*
    - db/migrate/20231220224223_create_good_jobs.rb
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - storage/**/*
    - tmp/**/*
    - vendor/**/*
  SuggestExtensions: false

Bundler/OrderedGems:
  Enabled: false

Capybara/CurrentPathExpectation:
  Enabled: false

Capybara/ClickLinkOrButtonStyle:
  EnforcedStyle: link_or_button

Capybara/NegationMatcher:
  Enabled: false

FactoryBot/AssociationStyle:
  Enabled: false

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

FactoryBot/IdSequence:
  Exclude:
    - spec/factories/api/**/*.rb

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Exclude:
    - spec/**/*

Layout/HashAlignment:
  EnforcedColonStyle:
    - key
    - table
  Exclude:
    - lib/tasks/auto_annotate_models.rake

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Max: 180
  Exclude:
    - spec/**/*
    - features/**/*
    - config/**/*

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Enabled: false

Rails:
  Enabled: true

Rails/ActionOrder:
  Enabled: false

Rails/ApplicationRecord:
  Exclude:
    - db/migrate/*.rb

Rails/ContentTag:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/DotSeparatedKeys:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/FindEach:
  Exclude:
    - app/views/**/*

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/auto_annotate_models.rake
    - lib/tasks/javascript.rake

Rails/RedundantPresenceValidationOnBelongsTo:
  Exclude:
    - app/forms/**/*.rb

Rails/SkipsModelValidations:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test

Rails/WhereNotWithMultipleConditions:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/SortMetadata:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpecRails/TravelAround:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: mixed

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/NestedTernaryOperator:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/OptionalBooleanParameter:
  Exclude:
    - app/jobs/**/*

Style/SymbolProc:
  Exclude:
    - config/initializers/rack_attack.rb

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma