default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: 0.0.0.0
  timeout: 5000

development:
  <<: *default
  database: hcktdevpr

test:
  <<: *default
  database: hcktdevpr

production:
  <<: *default
  database: hcktdevpr
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>